<!--TAB About-->
<section>
	<div class="container">
		<div class="about">
			<h2 class="title-about-h2">Hi, I'm Jo Anna </h2>
		</div>
		<div class="img-about">
			<img src="img/Estelle-picture-1.png" alt ="Estelle-picture-1"/>
		</div>
		<div class="text-about-1">
			<p>
				I'm a master student of Architecture in France and I'm passionate about Architecture, Art & Travelling. Now I like make Travel Pictures, Videos and Drawing. It's fun to share with you : my passions, work, travel, and hobbies.
			</p>
			<div class="text-about-2">
				<blockquote>
					<q>
						For artists trying to find their way, creativity will always be a winding path. Life is a wandering path sometimes, but creativity will bring you so much more than the normal day to day of almost anything else you could do.
					</q>
				</blockquote>
			</div>
		</div>
		<div class="text-about-3">
			<p>
				In our life, often we think about visiting to a country of our choice. We would definitely have a lot of reasons on why we want to visit to that particular country. It may be because of the beautiful tourist spots or it can be because of the culture of that country, etc... 
			</p>
					<div class="img-world-map">
					<figure>
						<img src="http://chart.apis.google.com/chart?cht=map:fixed=-70,-180,80,180&chs=450x300&chf=bg,s,336699&chco=d0d0d0,cc0000&chd=s:999999999999999&chld=GB|CH|ES|PT|FR|DE|GR|IT|LU|HR|BE|AT|BA|IN|CA" width="450" height="300" >
					<figcaption>My trips around the world</figcaption>
					</figure>
					</div>
				</p>
				I want to visit <strong>Cape Town</strong> its abundance of scenic beauty and natural attractions. The city itself is situated between the Atlantic Ocean and Table Mountain, one of the world's Seven Wonders of Nature... So, in the same way I want to know, if you were given a chance, which country you will select for a visit? And do give the proper reason on why you want to visit that country.
			</p>
			<p class="text-about-4">
				My dream trip : travel in 
				<strong>South Africa.</strong>
			</p>
		</div>
	</div>
</section>
