<!--Main - Homepage-->
<section>
	<div class="container">
		<div class="picture">
			<figure>
				<img class="picture-home" src="img/REEL.4.30.jpg" alt="pictureHome">
				<figcaption>
					Pictures 
					<a href="index.php?action=pictures"></a>
				</figcaption>
			</figure>
			<figure>
				<img class="picture-home" src="img/REEL.7.30.jpg" alt="pictureHome">
				<figcaption>
					Videos
					<a href="index.php?action=videos"></a>
				</figcaption>
			</figure>
			<figure>
				<img class="picture-home" src="img/REEL.5.30.jpg" alt="pictureHome">
				<figcaption>
					Drawing
					<a href="index.php?action=drawing"></a>
				</figcaption>
			</figure>
		</div>
	</div>
</section>

    
    