<!--MODIFY AN ARTICLE IN THE DATABASE-->
<?php if(isset($_SESSION['admin'])): ?>
<section>
	<div class="container">
		<div class="form">
			<form action="index.php?action=modifyArticle" method="post" enctype="multipart/form-data">
				<input type="hidden" name="idArticle" value="<?intval($post['idArticle']) ?>">
				<fieldset>
					<legend>
						<i class="fas fa-camera-retro"></i>
						Modifier un article 
					</legend>
					<input type="hidden" name="idArticle" value="<?=htmlspecialchars($modifyArticle["idArticle"]) ?>"/>
					<label for="categorie">Categorie</label>
					<select class="form-details" name="idCategorie" id="idCategorie">
						<option value="<?=htmlspecialchars($modifyArticle['idCategorie']) ?>"><?=htmlspecialchars($modifyArticle['nomCategorie']) ?></option>
						<?php foreach ($categories as $categorie):?>
						<option value="<?=htmlspecialchars($categorie["idCategorie"]) ?>"><?=htmlspecialchars($categorie["nomCategorie"]) ?></option>
						<?php endforeach; ?>
					</select>
					<label for="titre">Titre</label>
					<input class="form-details" type="text" name="titleArticle" id="titleArticle" value="<?=htmlspecialchars($modifyArticle["titre"]) ?>"/>
					<label for="description">Description</label>
					<textarea class="form-details-msg" name="contenu" rows="6" cols="40"><?=htmlspecialchars($modifyArticle["description"]) ?></textarea>
					<label for="media">Médias (Pictures-Videos-Drawing)</label>
					<img src="img/<?=htmlspecialchars($modifyArticle["media"]) ?>"/>
					<input class="form-details" type="file" name="media" id="media" value="<?=htmlspecialchars($modifyArticle["media"]) ?>"/>
					<div class="button">
						<div class="buttons">
							<input class="connexion-button" type="submit" value="Enregistrer">
						</div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</section>
<?php endif; ?>